name: Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['', 'stable']

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        go-version-file: 'go.mod'

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install libgles2-mesa-dev xvfb

    - name: Test
      run: xvfb-run go test -race ./...